"""QuantX Grid Bot template — Symmetric Grid Trading (buy-side, no short selling)."""

GRID_BOT_TEMPLATE = '''#!/usr/bin/env python3
"""
QuantX Grid Bot — {STRATEGY_ID}
Symmetric Grid Trading on {SYMBOL} (buy-side only)
Generated by QuantX Deployer
"""

import json
import math
import threading
import time
import urllib.request
from datetime import datetime, timezone, timedelta

from longport.openapi import (
    Config, OrderSide, OrderStatus, OrderType,
    QuoteContext, SubType, TimeInForceType,
    TopicType, TradeContext,
)

# ── Credentials ──────────────────────────────────
APP_KEY      = "{APP_KEY}"
APP_SECRET   = "{APP_SECRET}"
ACCESS_TOKEN = "{ACCESS_TOKEN}"

# ── Config ────────────────────────────────────────
STUDENT_EMAIL = "{STUDENT_EMAIL}"
STRATEGY_ID   = "{STRATEGY_ID}"
SYMBOL        = "{SYMBOL}"
LOT_SIZE      = {LOT_SIZE}
ARENA         = "{ARENA}"
API_URL       = "{API_URL}"
LOTS          = {LOTS}

# ── Grid Parameters ───────────────────────────────
GRID_LEVELS       = {GRID_LEVELS}
GRID_SPACING_PCT  = {GRID_SPACING_PCT}
TP_PCT            = {TP_PCT}
SL_BOUNDARY_PCT   = {SL_BOUNDARY_PCT}

SGT = timezone(timedelta(hours=8))


def log(msg):
    ts = datetime.now(SGT).strftime("%H:%M:%S.%f")[:-3]
    print(f"[{{ts}}][{{STRATEGY_ID}}] {{msg}}", flush=True)


# ── Grid State ────────────────────────────────────
cmp_reference      = 0.0
buy_levels         = []   # list of dicts
sell_levels_ref    = []   # pre-calculated but not placed at startup
cumulative_pnl     = 0.0
completed_cycles   = 0
last_price         = 0.0
stop_event         = threading.Event()
trade_ctx_ref      = None
position_qty       = 0


# ── HK Tick Size ──────────────────────────────────

def hk_tick_round(price, side="buy"):
    if ARENA != "HK":
        return round(price, 2)
    if price < 0.25: tick = 0.001
    elif price < 0.50: tick = 0.005
    elif price < 10: tick = 0.010
    elif price < 20: tick = 0.020
    elif price < 100: tick = 0.050
    elif price < 200: tick = 0.100
    elif price < 500: tick = 0.200
    elif price < 1000: tick = 0.500
    elif price < 2000: tick = 1.000
    elif price < 5000: tick = 2.000
    else: tick = 5.000
    if side == "buy":
        return round(math.floor(price / tick) * tick, 4)
    else:
        return round(math.ceil(price / tick) * tick, 4)


# ── Helpers ───────────────────────────────────────

def post_trade(side, price, qty, pnl):
    global cumulative_pnl
    cumulative_pnl += pnl
    body = json.dumps({{
        "email": STUDENT_EMAIL,
        "strategy_id": STRATEGY_ID,
        "symbol": SYMBOL,
        "side": side,
        "price": round(price, 4),
        "qty": qty,
        "pnl": round(pnl, 4),
    }}).encode()
    req = urllib.request.Request(
        f"{{API_URL}}/api/trade", data=body,
        headers={{"Content-Type": "application/json"}}, method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            result = json.loads(resp.read())
            log(f"Trade posted: {{side.upper()}} {{qty}} @ ${{price:.4f}} PnL=${{pnl:.2f}} Cum=${{result.get('cumulative_pnl', 0):.2f}}")
    except Exception as e:
        log(f"WARNING: trade post failed: {{e}}")


def post_heartbeat(payload):
    body = json.dumps({{
        "email": STUDENT_EMAIL,
        "vps_ip": "local",
        "bot_status": "running",
        "strategies": payload,
    }}).encode()
    req = urllib.request.Request(
        f"{{API_URL}}/api/heartbeat", data=body,
        headers={{"Content-Type": "application/json"}}, method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=5):
            pass
    except Exception as e:
        log(f"Heartbeat failed: {{e}}")


def submit_limit_order(trade_ctx, side, qty, price):
    qty = max(LOT_SIZE, (qty // LOT_SIZE) * LOT_SIZE)
    price = hk_tick_round(price, "buy" if side == OrderSide.Buy else "sell")
    side_str = "BUY" if side == OrderSide.Buy else "SELL"
    log(f"Submitting LIMIT {{side_str}} {{qty}} @ ${{price:.4f}}")
    try:
        resp = trade_ctx.submit_order(
            symbol=SYMBOL,
            order_type=OrderType.LO,
            side=side,
            submitted_quantity=qty,
            time_in_force=TimeInForceType.Day,
            submitted_price=price,
        )
        log(f"Order placed: order_id={{resp.order_id}}")
        return str(resp.order_id)
    except Exception as e:
        log(f"ERROR placing order: {{e}}")
        return ""


def cancel_order(trade_ctx, order_id):
    if not order_id:
        return
    try:
        trade_ctx.cancel_order(order_id)
        log(f"Cancelled order {{order_id}}")
    except Exception as e:
        log(f"WARNING: cancel failed for {{order_id}}: {{e}}")


# ── Grid Construction ─────────────────────────────

def build_grid(cmp):
    global buy_levels, sell_levels_ref, cmp_reference
    cmp_reference = cmp
    buy_levels = []
    sell_levels_ref = []
    spacing = cmp * GRID_SPACING_PCT / 100.0
    order_shares = LOTS * LOT_SIZE

    log(f"Building grid around CMP=${{cmp:.4f}}")
    log(f"  Spacing: {{GRID_SPACING_PCT}}% = ${{spacing:.4f}}")
    log(f"  TP: {{TP_PCT}}%")
    log(f"  Levels: {{GRID_LEVELS}} buy (sell placed on fill)")
    log(f"  Order size: {{order_shares}} shares")
    log(f"  SL boundary: {{SL_BOUNDARY_PCT}}%")

    # Buy levels below CMP — placed immediately
    for i in range(1, GRID_LEVELS + 1):
        entry = hk_tick_round(cmp - i * spacing, "buy")
        tp = hk_tick_round(entry * (1 + TP_PCT / 100), "sell")
        buy_levels.append({{
            "level_id": f"BUY_{{i}}",
            "side": "buy",
            "entry_price": entry,
            "tp_price": tp,
            "lots": order_shares,
            "filled": False,
            "active": False,
            "order_id": "",
            "tp_order_id": "",
            "entry_fill_price": 0.0,
        }})
        log(f"  [BUY_{{i}}]  entry=${{entry:.4f}}  TP=${{tp:.4f}}")

    # Sell levels above CMP — reference only, not placed at startup
    for i in range(1, GRID_LEVELS + 1):
        entry = hk_tick_round(cmp + i * spacing, "sell")
        sell_levels_ref.append({{
            "level_id": f"SELL_{{i}}",
            "price": entry,
        }})
        log(f"  [SELL_{{i}}] reference=${{entry:.4f}} (not placed at startup)")


def place_buy_grid(trade_ctx):
    log(f"Placing {{len(buy_levels)}} buy-side grid orders...")
    for level in buy_levels:
        oid = submit_limit_order(trade_ctx, OrderSide.Buy, level["lots"], level["entry_price"])
        level["order_id"] = oid
        level["active"] = bool(oid)
        time.sleep(0.3)
    active = sum(1 for l in buy_levels if l["active"])
    log(f"Buy-side grid placed: {{active}}/{{len(buy_levels)}} orders active")
    log(f"Sell orders will be placed as buys fill.")


def flatten_all(trade_ctx, reason):
    global position_qty
    log(f"FLATTEN ALL - reason: {{reason}}")

    for level in buy_levels:
        if level["active"] and level["order_id"]:
            cancel_order(trade_ctx, level["order_id"])
        if level["tp_order_id"]:
            cancel_order(trade_ctx, level["tp_order_id"])
        level["active"] = False
        level["filled"] = False

    if position_qty > 0:
        log(f"Closing net long position: SELL {{position_qty}}")
        try:
            trade_ctx.submit_order(
                symbol=SYMBOL,
                order_type=OrderType.MO,
                side=OrderSide.Sell,
                submitted_quantity=position_qty,
                time_in_force=TimeInForceType.Day,
            )
        except Exception as e:
            log(f"ERROR closing position: {{e}}")

    log("Flatten complete.")
    stop_event.set()


# ── Fill handler ──────────────────────────────────

def on_order_changed(event):
    global position_qty, completed_cycles

    if event.symbol != SYMBOL:
        return
    if event.status not in (OrderStatus.Filled, OrderStatus.PartialFilled):
        return

    fill_price = float(event.executed_price or 0)
    fill_qty = int(event.executed_quantity or 0)
    order_id = str(event.order_id)
    side_str = "buy" if event.side == OrderSide.Buy else "sell"

    log(f"FILL: {{side_str.upper()}} {{fill_qty}} @ ${{fill_price:.4f}} order_id={{order_id}}")

    for level in buy_levels:
        # ── Entry BUY fill → place TP SELL ──
        if level["order_id"] == order_id and not level["filled"]:
            level["filled"] = True
            level["entry_fill_price"] = fill_price
            position_qty += fill_qty
            post_trade("buy", fill_price, fill_qty, 0.0)

            # Place TP sell immediately
            tp_price = hk_tick_round(fill_price * (1 + TP_PCT / 100), "sell")
            tp_oid = submit_limit_order(trade_ctx_ref, OrderSide.Sell, fill_qty, tp_price)
            level["tp_order_id"] = tp_oid
            log(f"[{{level['level_id']}}] Bought @ ${{fill_price:.4f}} -> TP SELL placed @ ${{tp_price:.4f}}")
            return

        # ── TP SELL fill → PnL + replenish buy ──
        if level["tp_order_id"] == order_id and level["filled"]:
            entry_price = level["entry_fill_price"]
            pnl = (fill_price - entry_price) * fill_qty
            position_qty -= fill_qty
            completed_cycles += 1
            post_trade("sell", fill_price, fill_qty, round(pnl, 4))
            log(f"[{{level['level_id']}}] Sold @ ${{fill_price:.4f}} PnL=${{pnl:.2f}} — replenishing buy...")

            # Re-place buy limit at original entry price
            level["filled"] = False
            level["entry_fill_price"] = 0.0
            level["tp_order_id"] = ""
            new_oid = submit_limit_order(trade_ctx_ref, OrderSide.Buy, level["lots"], level["entry_price"])
            level["order_id"] = new_oid
            level["active"] = bool(new_oid)
            log(f"[{{level['level_id']}}] Buy replenished @ ${{level['entry_price']:.4f}} (cycle #{{completed_cycles}})")
            return


# ── SL boundary check ─────────────────────────────

def check_sl_boundary(price, trade_ctx):
    if not buy_levels:
        return
    lowest_entry = buy_levels[-1]["entry_price"]
    sl_price = lowest_entry * (1 - SL_BOUNDARY_PCT / 100)
    if price < sl_price:
        flatten_all(trade_ctx, f"Price ${{price:.4f}} below SL boundary ${{sl_price:.4f}} ({{SL_BOUNDARY_PCT}}% below lowest buy)")


# ── Quote handler ─────────────────────────────────

def on_quote(symbol, event):
    global last_price
    price = float(event.last_done or 0)
    if price <= 0 or symbol != SYMBOL:
        return
    last_price = price
    if trade_ctx_ref:
        check_sl_boundary(price, trade_ctx_ref)


# ── Heartbeat thread ──────────────────────────────

def heartbeat_thread():
    while not stop_event.is_set():
        time.sleep(60)
        if stop_event.is_set():
            break
        buy_active = sum(1 for l in buy_levels if l["active"] and not l["filled"])
        positions_held = sum(1 for l in buy_levels if l["filled"])
        payload = [{{
            "strategy_id": STRATEGY_ID,
            "indicator": "SYMMETRIC_GRID",
            "symbol": SYMBOL,
            "status": "running",
            "position": position_qty,
            "cumulative_pnl": round(cumulative_pnl, 4),
            "mode": "library",
            "details": {{
                "cmp_reference": cmp_reference,
                "buy_orders_active": buy_active,
                "positions_held": positions_held,
                "completed_cycles": completed_cycles,
                "last_price": last_price,
            }}
        }}]
        post_heartbeat(payload)


# ── Market Hours ──────────────────────────────────

def is_market_open():
    now = datetime.now(SGT)
    h, m = now.hour, now.minute
    if ARENA == "US":
        is_open = (h > 21 or (h == 21 and m >= 30) or h < 4)
        return is_open, "US market: 9:30pm-4:00am SGT"
    elif ARENA in ("HK", "HK_ETF"):
        is_open = ((h > 9 or (h == 9 and m >= 30)) and h < 16)
        return is_open, "HK market: 9:30am-4:00pm SGT"
    return True, "Unknown market"


def fetch_cmp_with_retry(quote_ctx, retries=3):
    for attempt in range(1, retries + 1):
        try:
            quotes = quote_ctx.quote([SYMBOL])
            if quotes:
                cmp = float(quotes[0].last_done)
                if cmp > 0:
                    return cmp
            log(f"Quote attempt {{attempt}}/{{retries}}: no data returned")
        except Exception as e:
            log(f"Quote attempt {{attempt}}/{{retries}} failed: {{e}}")
        if attempt < retries:
            log("Retrying in 5 seconds...")
            time.sleep(5)
    return None


# ── Main ──────────────────────────────────────────

def main():
    global trade_ctx_ref

    log("Starting Symmetric Grid Bot (buy-side only)")
    log(f"Symbol: {{SYMBOL}} | Levels: {{GRID_LEVELS}} buy | Spacing: {{GRID_SPACING_PCT}}% | TP: {{TP_PCT}}%")

    is_open, schedule = is_market_open()
    now_sgt = datetime.now(SGT).strftime("%H:%M SGT")
    log(f"Current time: {{now_sgt}} | {{schedule}} | {{'OPEN' if is_open else 'CLOSED'}}")

    config = Config(
        app_key=APP_KEY,
        app_secret=APP_SECRET,
        access_token=ACCESS_TOKEN,
    )

    trade_ctx = TradeContext(config)
    trade_ctx.set_on_order_changed(on_order_changed)
    trade_ctx_ref = trade_ctx
    trade_ctx.subscribe([TopicType.Private])
    log("TradeContext connected")

    quote_ctx = QuoteContext(config)

    # Fetch CMP with retry + market hours awareness
    log(f"Fetching current market price for {{SYMBOL}}...")
    cmp = fetch_cmp_with_retry(quote_ctx)

    if cmp is None:
        is_open, schedule = is_market_open()
        if not is_open:
            log(f"Market is currently CLOSED. {{schedule}}")
            log(f"Bot will wait and retry every 60 seconds until market opens...")
            while not stop_event.is_set():
                stop_event.wait(60)
                if stop_event.is_set():
                    log("Shutdown during wait.")
                    return
                is_open, _ = is_market_open()
                if is_open:
                    log("Market is now OPEN. Fetching quote...")
                    cmp = fetch_cmp_with_retry(quote_ctx)
                    if cmp:
                        break
                else:
                    log(f"Still waiting... {{datetime.now(SGT).strftime('%H:%M SGT')}}")
        else:
            log(f"Market should be open but quote failed after retries.")
            log(f"Check your LongPort subscription for {{SYMBOL}}")
            return

    if cmp is None:
        log("ERROR: Could not fetch CMP. Aborting.")
        return

    log(f"CMP fetched: ${{cmp:.4f}}")

    build_grid(cmp)
    place_buy_grid(trade_ctx)

    quote_ctx.set_on_quote(on_quote)
    quote_ctx.subscribe([SYMBOL], [SubType.Quote])
    log(f"Quote feed subscribed for {{SYMBOL}}")

    hb = threading.Thread(target=heartbeat_thread, daemon=True)
    hb.start()

    log("Grid is LIVE. Buy orders waiting for fills...")
    log(f"On each buy fill -> TP sell placed automatically")
    log(f"On each sell fill -> buy replenished automatically")
    sl_price = buy_levels[-1]["entry_price"] * (1 - SL_BOUNDARY_PCT / 100) if buy_levels else 0
    log(f"SL boundary: flatten if price drops below ${{sl_price:.4f}}")

    try:
        while not stop_event.is_set():
            stop_event.wait(1)
    except KeyboardInterrupt:
        log("Shutdown requested...")
    finally:
        log("Flattening all positions on shutdown...")
        flatten_all(trade_ctx, "Shutdown")
        log("Grid bot stopped.")


if __name__ == "__main__":
    main()
'''
